### ISSUE TITLE
Question about SmoothFullGrad

### ISSUE THREAD

**Issue by alfredonuhe** [idiap/fullgrad-saliency#12]
Why is it possible to determine the image size for FullGrad but not for SmoothFullGrad?

https://github.com/idiap/fullgrad-saliency/blob/26fb91b2f9ef616d15d080644b9f8a656a68204f/saliency/smooth_fullgrad.py#L30
https://github.com/idiap/fullgrad-saliency/blob/26fb91b2f9ef616d15d080644b9f8a656a68204f/saliency/fullgrad.py#L20

Thank you

**Comment by suraj-srinivas** [comment]
Hi, I think that was just oversight. I have corrected this now. Thanks for bringing it up!
